package workshop.repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import workshop.model.FinishStatistic;
import workshop.model.StatisticReport;

public interface FinishStatisticMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finish_statistic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finish_statistic
     *
     * @mbggenerated
     */
    int insert(FinishStatistic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finish_statistic
     *
     * @mbggenerated
     */
    int insertSelective(FinishStatistic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finish_statistic
     *
     * @mbggenerated
     */
    FinishStatistic selectByPrimaryKey(Integer id);

    List<FinishStatistic> searchBySql(@Param("sql") String sql);
    List<StatisticReport> searchGroup1(@Param("up_down_id") String updwonid,@Param("beg_time")String beg_time,
    		@Param("end_time")String end_time);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finish_statistic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FinishStatistic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finish_statistic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FinishStatistic record);
}