package workshop.repository;

import java.util.List;

import workshop.model.PtDept;

public interface PtDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_dept
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_dept
     *
     * @mbggenerated
     */
    int insert(PtDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_dept
     *
     * @mbggenerated
     */
    int insertSelective(PtDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_dept
     *
     * @mbggenerated
     */
    PtDept selectByPrimaryKey(Integer id);

    List<PtDept> selectALL();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_dept
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PtDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_dept
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PtDept record);
}