package workshop.repository;

import java.util.List;

import workshop.model.PtRole;

public interface PtRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String roleCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role
     *
     * @mbggenerated
     */
    int insert(PtRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role
     *
     * @mbggenerated
     */
    int insertSelective(PtRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role
     *
     * @mbggenerated
     */
    PtRole selectByPrimaryKey(String roleCode);

    List<PtRole> selectAll();
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PtRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PtRole record);
}