package workshop.repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import workshop.model.Reward;

public interface RewardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    int insert(Reward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    int insertSelective(Reward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    Reward selectByPrimaryKey(Integer id);

    List<Reward> searchBySql(@Param("sql") String sql);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Reward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Reward record);
}