package workshop.repository;

import java.util.List;

import workshop.model.SystemParam;

public interface SystemParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param
     *
     * @mbggenerated
     */
    int insert(SystemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param
     *
     * @mbggenerated
     */
    int insertSelective(SystemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param
     *
     * @mbggenerated
     */
    SystemParam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemParam record);
    
    List<SystemParam> selectAll();
}