package workshop.model;

import java.util.Date;

public class Attendance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.up_down_id
     *
     * @mbggenerated
     */
    private String upDownId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.dept_name
     *
     * @mbggenerated
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.beg_time
     *
     * @mbggenerated
     */
    private Date begTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.id
     *
     * @return the value of attendance.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.id
     *
     * @param id the value for attendance.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.phone
     *
     * @return the value of attendance.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.phone
     *
     * @param phone the value for attendance.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.user_name
     *
     * @return the value of attendance.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.user_name
     *
     * @param userName the value for attendance.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.up_down_id
     *
     * @return the value of attendance.up_down_id
     *
     * @mbggenerated
     */
    public String getUpDownId() {
        return upDownId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.up_down_id
     *
     * @param upDownId the value for attendance.up_down_id
     *
     * @mbggenerated
     */
    public void setUpDownId(String upDownId) {
        this.upDownId = upDownId == null ? null : upDownId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.dept_name
     *
     * @return the value of attendance.dept_name
     *
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.dept_name
     *
     * @param deptName the value for attendance.dept_name
     *
     * @mbggenerated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.type
     *
     * @return the value of attendance.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }
    
    public String getTypeName() {
    	String name="未知";
    	if(type==0){
    		name="正常上班";
    	}
    	else if(type==1){
    		name="请假";
    	}
    	else if(type==2){
    		name="加班";
    	}
    	
        return name;
    }
    

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.type
     *
     * @param type the value for attendance.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.beg_time
     *
     * @return the value of attendance.beg_time
     *
     * @mbggenerated
     */
    public Date getBegTime() {
        return begTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.beg_time
     *
     * @param begTime the value for attendance.beg_time
     *
     * @mbggenerated
     */
    public void setBegTime(Date begTime) {
        this.begTime = begTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.end_time
     *
     * @return the value of attendance.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.end_time
     *
     * @param endTime the value for attendance.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.remark
     *
     * @return the value of attendance.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.remark
     *
     * @param remark the value for attendance.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}