package workshop.model;

import java.math.BigDecimal;
import java.util.Date;

public class FinishStatistic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finish_statistic.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finish_statistic.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finish_statistic.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finish_statistic.up_down_id
     *
     * @mbggenerated
     */
    private String upDownId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finish_statistic.dept_name
     *
     * @mbggenerated
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finish_statistic.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finish_statistic.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finish_statistic.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finish_statistic.get_money
     *
     * @mbggenerated
     */
    private BigDecimal getMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finish_statistic.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finish_statistic.add_user_id
     *
     * @mbggenerated
     */
    private Integer addUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finish_statistic.add_user_name
     *
     * @mbggenerated
     */
    private String addUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finish_statistic.id
     *
     * @return the value of finish_statistic.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finish_statistic.id
     *
     * @param id the value for finish_statistic.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finish_statistic.phone
     *
     * @return the value of finish_statistic.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finish_statistic.phone
     *
     * @param phone the value for finish_statistic.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finish_statistic.user_name
     *
     * @return the value of finish_statistic.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finish_statistic.user_name
     *
     * @param userName the value for finish_statistic.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finish_statistic.up_down_id
     *
     * @return the value of finish_statistic.up_down_id
     *
     * @mbggenerated
     */
    public String getUpDownId() {
        return upDownId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finish_statistic.up_down_id
     *
     * @param upDownId the value for finish_statistic.up_down_id
     *
     * @mbggenerated
     */
    public void setUpDownId(String upDownId) {
        this.upDownId = upDownId == null ? null : upDownId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finish_statistic.dept_name
     *
     * @return the value of finish_statistic.dept_name
     *
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finish_statistic.dept_name
     *
     * @param deptName the value for finish_statistic.dept_name
     *
     * @mbggenerated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finish_statistic.product_id
     *
     * @return the value of finish_statistic.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finish_statistic.product_id
     *
     * @param productId the value for finish_statistic.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finish_statistic.product_name
     *
     * @return the value of finish_statistic.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finish_statistic.product_name
     *
     * @param productName the value for finish_statistic.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finish_statistic.num
     *
     * @return the value of finish_statistic.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finish_statistic.num
     *
     * @param num the value for finish_statistic.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finish_statistic.get_money
     *
     * @return the value of finish_statistic.get_money
     *
     * @mbggenerated
     */
    public BigDecimal getGetMoney() {
        return getMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finish_statistic.get_money
     *
     * @param getMoney the value for finish_statistic.get_money
     *
     * @mbggenerated
     */
    public void setGetMoney(BigDecimal getMoney) {
        this.getMoney = getMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finish_statistic.addtime
     *
     * @return the value of finish_statistic.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finish_statistic.addtime
     *
     * @param addtime the value for finish_statistic.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finish_statistic.add_user_id
     *
     * @return the value of finish_statistic.add_user_id
     *
     * @mbggenerated
     */
    public Integer getAddUserId() {
        return addUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finish_statistic.add_user_id
     *
     * @param addUserId the value for finish_statistic.add_user_id
     *
     * @mbggenerated
     */
    public void setAddUserId(Integer addUserId) {
        this.addUserId = addUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finish_statistic.add_user_name
     *
     * @return the value of finish_statistic.add_user_name
     *
     * @mbggenerated
     */
    public String getAddUserName() {
        return addUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finish_statistic.add_user_name
     *
     * @param addUserName the value for finish_statistic.add_user_name
     *
     * @mbggenerated
     */
    public void setAddUserName(String addUserName) {
        this.addUserName = addUserName == null ? null : addUserName.trim();
    }
}