package workshop.model;

public class PtDept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_dept.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_dept.dept_name
     *
     * @mbggenerated
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_dept.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_dept.up_down_id
     *
     * @mbggenerated
     */
    private String upDownId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_dept.id
     *
     * @return the value of pt_dept.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_dept.id
     *
     * @param id the value for pt_dept.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_dept.dept_name
     *
     * @return the value of pt_dept.dept_name
     *
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_dept.dept_name
     *
     * @param deptName the value for pt_dept.dept_name
     *
     * @mbggenerated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_dept.parent_id
     *
     * @return the value of pt_dept.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_dept.parent_id
     *
     * @param parentId the value for pt_dept.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_dept.up_down_id
     *
     * @return the value of pt_dept.up_down_id
     *
     * @mbggenerated
     */
    public String getUpDownId() {
        return upDownId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_dept.up_down_id
     *
     * @param upDownId the value for pt_dept.up_down_id
     *
     * @mbggenerated
     */
    public void setUpDownId(String upDownId) {
        this.upDownId = upDownId == null ? null : upDownId.trim();
    }
}