package workshop.model;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

public class PtUser implements UserDetails{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	 
    private Integer id;

    
    private String phone;

    
    private String userPwd;

     
    private String bodyId;
 
    private String address;

     
    private String roleCode;

    
    private String roleName;

    
    private Integer deptId;
 
    private String deptName;

   
    private String realName;
 
    private String picUrl;
 
    private Boolean sex;
 
    private Date addTime;

    
    private Date leaveTime;

    
    private Date loginTime;

   
    private Byte state;

    
    private String upDownId;

    
    private String jobName;
 
    private Integer fixMoney;

     
    private Byte workDays;

     
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_user.id
     *
     * @param id the value for pt_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_user.phone
     *
     * @return the value of pt_user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_user.phone
     *
     * @param phone the value for pt_user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_user.user_pwd
     *
     * @return the value of pt_user.user_pwd
     *
     * @mbggenerated
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_user.user_pwd
     *
     * @param userPwd the value for pt_user.user_pwd
     *
     * @mbggenerated
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_user.body_id
     *
     * @return the value of pt_user.body_id
     *
     * @mbggenerated
     */
    public String getBodyId() {
        return bodyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_user.body_id
     *
     * @param bodyId the value for pt_user.body_id
     *
     * @mbggenerated
     */
    public void setBodyId(String bodyId) {
        this.bodyId = bodyId == null ? null : bodyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_user.address
     *
     * @return the value of pt_user.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_user.address
     *
     * @param address the value for pt_user.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_user.role_code
     *
     * @return the value of pt_user.role_code
     *
     * @mbggenerated
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_user.role_code
     *
     * @param roleCode the value for pt_user.role_code
     *
     * @mbggenerated
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_user.role_name
     *
     * @return the value of pt_user.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_user.role_name
     *
     * @param roleName the value for pt_user.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_user.dept_id
     *
     * @return the value of pt_user.dept_id
     *
     * @mbggenerated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_user.dept_id
     *
     * @param deptId the value for pt_user.dept_id
     *
     * @mbggenerated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_user.dept_name
     *
     * @return the value of pt_user.dept_name
     *
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_user.dept_name
     *
     * @param deptName the value for pt_user.dept_name
     *
     * @mbggenerated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_user.real_name
     *
     * @return the value of pt_user.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_user.real_name
     *
     * @param realName the value for pt_user.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_user.pic_url
     *
     * @return the value of pt_user.pic_url
     *
     * @mbggenerated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_user.pic_url
     *
     * @param picUrl the value for pt_user.pic_url
     *
     * @mbggenerated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_user.sex
     *
     * @return the value of pt_user.sex
     *
     * @mbggenerated
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_user.sex
     *
     * @param sex the value for pt_user.sex
     *
     * @mbggenerated
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_user.add_time
     *
     * @return the value of pt_user.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_user.add_time
     *
     * @param addTime the value for pt_user.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_user.leave_time
     *
     * @return the value of pt_user.leave_time
     *
     * @mbggenerated
     */
    public Date getLeaveTime() {
        return leaveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_user.leave_time
     *
     * @param leaveTime the value for pt_user.leave_time
     *
     * @mbggenerated
     */
    public void setLeaveTime(Date leaveTime) {
        this.leaveTime = leaveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_user.login_time
     *
     * @return the value of pt_user.login_time
     *
     * @mbggenerated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_user.login_time
     *
     * @param loginTime the value for pt_user.login_time
     *
     * @mbggenerated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_user.state
     *
     * @return the value of pt_user.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_user.state
     *
     * @param state the value for pt_user.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_user.up_down_id
     *
     * @return the value of pt_user.up_down_id
     *
     * @mbggenerated
     */
    public String getUpDownId() {
        return upDownId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_user.up_down_id
     *
     * @param upDownId the value for pt_user.up_down_id
     *
     * @mbggenerated
     */
    public void setUpDownId(String upDownId) {
        this.upDownId = upDownId == null ? null : upDownId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_user.job_name
     *
     * @return the value of pt_user.job_name
     *
     * @mbggenerated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_user.job_name
     *
     * @param jobName the value for pt_user.job_name
     *
     * @mbggenerated
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_user.fix_money
     *
     * @return the value of pt_user.fix_money
     *
     * @mbggenerated
     */
    public Integer getFixMoney() {
        return fixMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_user.fix_money
     *
     * @param fixMoney the value for pt_user.fix_money
     *
     * @mbggenerated
     */
    public void setFixMoney(Integer fixMoney) {
        this.fixMoney = fixMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_user.work_days
     *
     * @return the value of pt_user.work_days
     *
     * @mbggenerated
     */
    public Byte getWorkDays() {
        return workDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_user.work_days
     *
     * @param workDays the value for pt_user.work_days
     *
     * @mbggenerated
     */
    public void setWorkDays(Byte workDays) {
        this.workDays = workDays;
    }

	@Override
	public Collection<? extends GrantedAuthority> getAuthorities() {
		// TODO Auto-generated method stub
		List<GrantedAuthority> authorities = new ArrayList<>();
		authorities.add(new SimpleGrantedAuthority(this.roleCode));
		return authorities;
	}

	@Override
	public String getPassword() {
		// TODO Auto-generated method stub
		return this.userPwd;
	}

	@Override
	public String getUsername() {
		// TODO Auto-generated method stub
		return this.phone;
	}

	@Override
	public boolean isAccountNonExpired() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public boolean isAccountNonLocked() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public boolean isCredentialsNonExpired() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public boolean isEnabled() {
		// TODO Auto-generated method stub
		return state==0 ? true : false;
	}
}