package workshop.model;

import java.math.BigDecimal;

public class Reward {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.up_down_id
     *
     * @mbggenerated
     */
    private String upDownId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.dept_name
     *
     * @mbggenerated
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.money
     *
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.obj_month
     *
     * @mbggenerated
     */
    private String objMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.add_user_phone
     *
     * @mbggenerated
     */
    private String addUserPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.add_user_name
     *
     * @mbggenerated
     */
    private String addUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.id
     *
     * @return the value of reward.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.id
     *
     * @param id the value for reward.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.phone
     *
     * @return the value of reward.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.phone
     *
     * @param phone the value for reward.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.user_name
     *
     * @return the value of reward.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.user_name
     *
     * @param userName the value for reward.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.up_down_id
     *
     * @return the value of reward.up_down_id
     *
     * @mbggenerated
     */
    public String getUpDownId() {
        return upDownId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.up_down_id
     *
     * @param upDownId the value for reward.up_down_id
     *
     * @mbggenerated
     */
    public void setUpDownId(String upDownId) {
        this.upDownId = upDownId == null ? null : upDownId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.dept_name
     *
     * @return the value of reward.dept_name
     *
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.dept_name
     *
     * @param deptName the value for reward.dept_name
     *
     * @mbggenerated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.money
     *
     * @return the value of reward.money
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.money
     *
     * @param money the value for reward.money
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.remark
     *
     * @return the value of reward.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.remark
     *
     * @param remark the value for reward.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.obj_month
     *
     * @return the value of reward.obj_month
     *
     * @mbggenerated
     */
    public String getObjMonth() {
        return objMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.obj_month
     *
     * @param objMonth the value for reward.obj_month
     *
     * @mbggenerated
     */
    public void setObjMonth(String objMonth) {
        this.objMonth = objMonth == null ? null : objMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.add_user_phone
     *
     * @return the value of reward.add_user_phone
     *
     * @mbggenerated
     */
    public String getAddUserPhone() {
        return addUserPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.add_user_phone
     *
     * @param addUserPhone the value for reward.add_user_phone
     *
     * @mbggenerated
     */
    public void setAddUserPhone(String addUserPhone) {
        this.addUserPhone = addUserPhone == null ? null : addUserPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.add_user_name
     *
     * @return the value of reward.add_user_name
     *
     * @mbggenerated
     */
    public String getAddUserName() {
        return addUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.add_user_name
     *
     * @param addUserName the value for reward.add_user_name
     *
     * @mbggenerated
     */
    public void setAddUserName(String addUserName) {
        this.addUserName = addUserName == null ? null : addUserName.trim();
    }
}